In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("data/final.csv")
data.head()

/var/folders/2x/6_yk_ybn3k1dgqyhmb23fpt40000gn/T/ipykernel_2123/3093107730.py:1: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("data/final.csv")


ID  Price (billion VND)  Area (m2) Property Type  Bedrooms  \
0  ABC118222                 1.77      54.10        Căn hộ       2.0   
1  A01198772                20.00     104.00        Căn hộ       2.0   
2   A0289931                18.00      91.57        Căn hộ       2.0   
3   A0287287                10.50      63.94        Căn hộ       1.0   
4  A02198668                16.50      92.30        Căn hộ       2.0   

   Bathrooms                                 Address Law Document   Post Date  \
0        1.0             Số 4, Phong Phú, Bình Chánh      So hong  2024-09-11   
1        2.0  Nguyễn Thị Minh Khai, Bến Nghé, Quận 1     Hop đong  2024-08-30   
2        2.0          Mai Chí Thọ, Thủ Thiêm, Quận 2     Hop đong  2024-08-04   
3        1.0          Mai Chí Thọ, Thủ Thiêm, Quận 2     Hop đong  2024-08-04   
4        2.0          Mai Chí Thọ, Thủ Thiêm, Quận 2     Hop đong  2024-08-04   

    Latitude   Longitude  Postal Code  Importance  Place Rank City  
0  10.714894  106.640598      72900.0    0.000067        30.0  HCM  
1  10.770974  106.702470      71010.0    0.053400        26.0  HCM  
2  10.774573  106.724893      72806.0    0.053400        26.0  HCM  
3  10.774573  106.724893      72806.0    0.053400        26.0  HCM  
4  10.774573  106.724893      72806.0    0.053400        26.0  HCM

In [3]:
# drop ID
data.drop(["ID"], axis=1, inplace=True)
data.head()

Price (billion VND)  Area (m2) Property Type  Bedrooms  Bathrooms  \
0                 1.77      54.10        Căn hộ       2.0        1.0   
1                20.00     104.00        Căn hộ       2.0        2.0   
2                18.00      91.57        Căn hộ       2.0        2.0   
3                10.50      63.94        Căn hộ       1.0        1.0   
4                16.50      92.30        Căn hộ       2.0        2.0   

                                  Address Law Document   Post Date   Latitude  \
0             Số 4, Phong Phú, Bình Chánh      So hong  2024-09-11  10.714894   
1  Nguyễn Thị Minh Khai, Bến Nghé, Quận 1     Hop đong  2024-08-30  10.770974   
2          Mai Chí Thọ, Thủ Thiêm, Quận 2     Hop đong  2024-08-04  10.774573   
3          Mai Chí Thọ, Thủ Thiêm, Quận 2     Hop đong  2024-08-04  10.774573   
4          Mai Chí Thọ, Thủ Thiêm, Quận 2     Hop đong  2024-08-04  10.774573   

    Longitude  Postal Code  Importance  Place Rank City  
0  106.640598      72900.0    0.000067        30.0  HCM  
1  106.702470      71010.0    0.053400        26.0  HCM  
2  106.724893      72806.0    0.053400        26.0  HCM  
3  106.724893      72806.0    0.053400        26.0  HCM  
4  106.724893      72806.0    0.053400        26.0  HCM

In [5]:
data.dropna(inplace=True, ignore_index=True)

In [9]:
# check data information
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36116 entries, 0 to 36115
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Price (billion VND)  36116 non-null  float64
 1   Area (m2)            36116 non-null  float64
 2   Property Type        36116 non-null  object 
 3   Bedrooms             36116 non-null  float64
 4   Bathrooms            36116 non-null  float64
 5   Address              36116 non-null  object 
 6   Law Document         36116 non-null  object 
 7   Quarter              36116 non-null  float64
 8   Year                 36116 non-null  float64
 9   Latitude             36116 non-null  float64
 10  Longitude            36116 non-null  float64
 11  Postal Code          36116 non-null  float64
 12  Importance           36116 non-null  float64
 13  Place Rank           36116 non-null  float64
 14  City                 36116 non-null  object 
dtypes: float64(11), object(4)
memory usa

**Need to encode non-numeric features: Property type, address, law doc, city**

*(?)split post date to get year and quarter, or use datetime data type*

In [7]:
post_dates = data["Post Date"].to_list()
print(len(post_dates))

36116


In [8]:
year = []
quarter = []
for date in post_dates:
    d = date.split("-")
    year.append(int(d[0]))
    month = int(d[1])
    if 1 <= month <= 3: quarter.append(1)
    elif 4 <= month <= 6: quarter.append(2)
    elif 7 <= month <= 9: quarter.append(3)
    elif 10 <= month <= 12: quarter.append(4)
    else: quarter.append(0)

year = pd.Series(year, dtype=np.float64)
quarter = pd.Series(quarter, dtype=np.float64)

data.insert(loc=7, column="Year", value=year)
data.insert(loc=7, column="Quarter", value=quarter)
data.drop(["Post Date"], axis=1, inplace=True)

data.head()

Price (billion VND)  Area (m2) Property Type  Bedrooms  Bathrooms  \
0                 1.77      54.10        Căn hộ       2.0        1.0   
1                20.00     104.00        Căn hộ       2.0        2.0   
2                18.00      91.57        Căn hộ       2.0        2.0   
3                10.50      63.94        Căn hộ       1.0        1.0   
4                16.50      92.30        Căn hộ       2.0        2.0   

                                  Address Law Document  Quarter    Year  \
0             Số 4, Phong Phú, Bình Chánh      So hong      3.0  2024.0   
1  Nguyễn Thị Minh Khai, Bến Nghé, Quận 1     Hop đong      3.0  2024.0   
2          Mai Chí Thọ, Thủ Thiêm, Quận 2     Hop đong      3.0  2024.0   
3          Mai Chí Thọ, Thủ Thiêm, Quận 2     Hop đong      3.0  2024.0   
4          Mai Chí Thọ, Thủ Thiêm, Quận 2     Hop đong      3.0  2024.0   

    Latitude   Longitude  Postal Code  Importance  Place Rank City  
0  10.714894  106.640598      72900.0    0.000067        30.0  HCM  
1  10.770974  106.702470      71010.0    0.053400        26.0  HCM  
2  10.774573  106.724893      72806.0    0.053400        26.0  HCM  
3  10.774573  106.724893      72806.0    0.053400        26.0  HCM  
4  10.774573  106.724893      72806.0    0.053400        26.0  HCM

In [10]:
data["Address"].unique().shape

(7619,)

In [11]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split

In [12]:
encoder = OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1, encoded_missing_value=-1)

In [13]:
encoded_features = encoder.fit_transform(data[["Property Type", "Address", "Law Document", "City"]])
print(encoded_features)

[[0.000e+00 5.025e+03 6.000e+00 0.000e+00]
 [0.000e+00 3.996e+03 4.000e+00 0.000e+00]
 [0.000e+00 3.266e+03 4.000e+00 0.000e+00]
 ...
 [4.000e+00 4.330e+02 2.000e+00 1.000e+00]
 [4.000e+00 6.902e+03 5.000e+00 1.000e+00]
 [4.000e+00 5.541e+03 5.000e+00 1.000e+00]]


In [14]:
encoder.categories_

[array(['Căn hộ', 'Căn hộ Studio', 'Nhà phố', 'Nhà riêng', 'biệt thự'],
       dtype=object),
 array(['- Biet thu, Đuong Nguyen Đuc Thuan, Đang Xa, Gia Lam, Ha Noi',
        '- Biet thu, Đuong QL 5, Đang Xa, Gia Lam, Ha Noi',
        '- Lien ke, La Khe, Kien Hung, Ha Đong, Ha Noi', ...,
        'Ấp Đông 1 - 2, Thới Tam Thôn, Hóc Môn',
        'Ấp Đông 1, Thới Tam Thôn, Hóc Môn', 'Ụ Ghe, Tam Phú, Thủ Đức'],
       dtype=object),
 array(['Chu quyen tu nhan', 'Giay tay', 'Giay to hop le', 'Giay đo',
        'Hop đong', 'KXĐ', 'So hong', 'Đang hop thuc hoa'], dtype=object),
 array(['HCM', 'HN'], dtype=object)]

In [15]:
data["Property Type"] = encoded_features[:, 0]
data["Address"] = encoded_features[:, 1]
data["Law Document"] = encoded_features[:, 2]
data["City"] = encoded_features[:, 3]

In [16]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36116 entries, 0 to 36115
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Price (billion VND)  36116 non-null  float64
 1   Area (m2)            36116 non-null  float64
 2   Property Type        36116 non-null  float64
 3   Bedrooms             36116 non-null  float64
 4   Bathrooms            36116 non-null  float64
 5   Address              36116 non-null  float64
 6   Law Document         36116 non-null  float64
 7   Quarter              36116 non-null  float64
 8   Year                 36116 non-null  float64
 9   Latitude             36116 non-null  float64
 10  Longitude            36116 non-null  float64
 11  Postal Code          36116 non-null  float64
 12  Importance           36116 non-null  float64
 13  Place Rank           36116 non-null  float64
 14  City                 36116 non-null  float64
dtypes: float64(15)
memory usage: 4.1 MB


In [17]:
# save encoder and data
import pickle as pkl

In [31]:
pkl.dump(encoder, open("CategoricalDataEncoder.h5", 'wb'))

In [27]:
X = data.iloc[:, 1:]
y = data.iloc[:, 0]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=True)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(28892, 14) (7224, 14) (28892,) (7224,)


In [28]:
X_train.insert(loc=X_train.shape[1], column="Price (billion VND)", value=y_train)
X_test.insert(loc=X_test.shape[1], column="Price (billion VND)", value=y_test)

X_train.to_csv("data/train_data.csv")
X_test.to_csv("data/test_data.csv")